### ISSUE TITLE
Benchmark run fails on python3.8

### ISSUE THREAD

**Issue by suzhoum** [autogluon/autogluon-bench#26]
> agbench run sample_configs/local_configs.yaml
Traceback (most recent call last):
  File "/opt/conda/envs/bench/bin/agbench", line 5, in <module>
    from autogluon.bench.main import app
  File "/home/ubuntu/yinweisu/autogluon-bench/src/autogluon/bench/main.py", line 4, in <module>
    from autogluon.bench.runbenchmark import get_job_status, run
  File "/home/ubuntu/yinweisu/autogluon-bench/src/autogluon/bench/runbenchmark.py", line 220, in <module>
    config_file: Optional[str] = None, job_ids: Optional[list[str]] = None, aws_region: Optional[str] = None
TypeError: 'type' object is not subscriptable

**Comment by suzhoum** [comment]
Fixed in https://github.com/autogluon/autogluon-bench/pull/28
